README.md, samples/jobs/describe_job_execution/main.cpp, samples/shadow/shadow_sync/main.cpp
State dependency on aws-crt-cpp v0.1.4, which brings along several improvements to MQTT keepalive and reconnect behavior.
=> aws-crt-cpp v0.1.4

CMakeLists.txt, README.md, discovery/CMakeLists.txt, discovery/cmake/Discovery-cpp-config.cmake, discovery/include/aws/discovery/ConnectivityInfo.h, discovery/include/aws/discovery/DiscoverResponse.h, discovery/include/aws/discovery/DiscoveryClient.h, discovery/include/aws/discovery/Exports.h, discovery/include/aws/discovery/GGCore.h, discovery/include/aws/discovery/GGGroup.h, discovery/source/ConnectivityInfo.cpp, discovery/source/DiscoverResponse.cpp, discovery/source/DiscoveryClient.cpp, discovery/source/GGCore.cpp, discovery/source/GGGroup.cpp, format-check.sh, jobs/source/GetPendingJobExecutionsResponse.cpp, jobs/source/JobExecutionsChangedEvent.cpp, samples/greengrass/basic_discovery/CMakeLists.txt, samples/greengrass/basic_discovery/main.cpp, samples/jobs/describe_job_execution/main.cpp, samples/shadow/shadow_sync/main.cpp
=> Gg discovery

discovery/include/aws/discovery/ConnectivityInfo.h, discovery/include/aws/discovery/DiscoverResponse.h, discovery/include/aws/discovery/DiscoveryClient.h, discovery/include/aws/discovery/Exports.h, discovery/include/aws/discovery/GGCore.h, discovery/include/aws/discovery/GGGroup.h, discovery/source/ConnectivityInfo.cpp, discovery/source/DiscoverResponse.cpp, discovery/source/DiscoveryClient.cpp, discovery/source/GGCore.cpp, discovery/source/GGGroup.cpp, jobs/source/JobStatus.cpp, jobs/source/RejectedErrorCode.cpp
- Add missing `#include <assert.h>` to enum-handling cpp files.
- Change assert() -> AWS_ASSERT() in input-validating discovery code.
- Run formatter on discovery code.
=> assert issues

README.md, codebuild/common-posix.sh, codebuild/common-windows.bat, codebuild/linux-clang3-x64.yml, codebuild/linux-clang6-x64.yml, codebuild/linux-gcc-4x-x64.yml, codebuild/linux-gcc-4x-x86.yml, codebuild/linux-gcc-5x-x64.yml, codebuild/linux-gcc-6x-x64.yml, codebuild/linux-gcc-7x-x64.yml, codebuild/windows-msvc-2015-x86.yml, codebuild/windows-msvc-2015.yml, codebuild/windows-msvc-2017.yml, format-check.sh, samples/greengrass/basic_discovery/main.cpp, samples/jobs/describe_job_execution/main.cpp, samples/shadow/shadow_sync/main.cpp
=> continuous integration

samples/shadow/shadow_sync/main.cpp
Updated s_changeShadowValue method to construct updateShadowRequest using ShadowState instead of using completely JsonObject
=> Updated s_changeShadowValue method

README.md, codebuild/common-posix.sh, codebuild/common-windows.bat, samples/greengrass/basic_discovery/main.cpp, samples/jobs/describe_job_execution/main.cpp, samples/shadow/shadow_sync/main.cpp
=> Update CRT to v0.4.6 for better error handling

discovery/source/DiscoveryClient.cpp, samples/greengrass/basic_discovery/main.cpp
Fixes for issue https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/issues/53
I'm entering backlog tasks to do a better job on each of these fixes:
- aws-crt-cpp and cpp-v2 should be defining their own `AWS_ERROR_` codes, rather than passing `AWS_ERROR_UNKNOWN` whenever something goes wrong outside of c-town.
- `WithCertificateAuthority()` and `OverrideDefaultTrustStore()` functions should have different names for whether you want to load a file or pass a in-imemory buffer. They should not rely on argument overloads.
=> Fix GreenGrass discovery

CMakeLists.txt, README.md, aws-common-runtime/CMakeLists.txt, aws-common-runtime/cmake/BuildAwsCrtCpp.cmake, codebuild/common-posix.sh, codebuild/common-windows.bat
=> Updated CI to use build deps, updated readme, and aws-crt-cpp version.

README.md, aws-common-runtime/CMakeLists.txt
=> Update readme for GA, and dependencies to latest crt.

samples/jobs/describe_job_execution/main.cpp, samples/shadow/shadow_sync/main.cpp
builder pattern doesn't look as cool anymore, but what are you gonna do
=> Fix error in samples when "--ca_file" not provided

CMakeLists.txt, README.md, samples/mqtt/basic_pub_sub/CMakeLists.txt, samples/mqtt/basic_pub_sub/main.cpp, samples/mqtt/raw_pub_sub/CMakeLists.txt, samples/mqtt/raw_pub_sub/main.cpp
Move C++ pub-sub samples from CRT to SDK.
User asked where the V2 SDK's pubsub sample was, and I didn't want to tell them "dig into your build directory to find the sample that was pulled down during configure"
Related PR where samples are removed from CRT: https://github.com/awslabs/aws-crt-cpp/pull/85
=> Move pubsub samples to SDK

.github/workflows/ci.yml, .github/workflows/lint.yml, builder.json
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/99
=> Update C and CRT dependencies

.github/ISSUE_TEMPLATE/---bug-report.md, .github/ISSUE_TEMPLATE/---questions-help.md, .github/workflows/stale_issue.yml
NA
Added a new github action it will:
- check for ancient issues (more than a year with no update) : it will message and mark for closing soon.
- check for stale issues (more than a week with no update) : same but different message prompting for update.
- check for closing soon label and close issues that have not been updated for 3 days after labeled.
=> new action for stale issue cleanup

samples/greengrass/basic_discovery/main.cpp, samples/identity/fleet_provisioning/main.cpp, samples/jobs/describe_job_execution/main.cpp, samples/mqtt/basic_pub_sub/main.cpp, samples/mqtt/raw_pub_sub/main.cpp, samples/shadow/shadow_sync/main.cpp
Possible dead lock without the predicate, and the onSubAck will show the subscription success even if the errorCode raised.
Related to https://github.com/awslabs/aws-c-mqtt/issues/136
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/88
- add predicate for each conditionVariable.wait()
- changed the booleans in basic_sub_pub & raw_sub_pub to atomic
- Fixed the onSubAck callback to check the error code and QoS returned.
=> Samples fix

README.md, samples/README.md, samples/greengrass/basic_discovery/main.cpp, samples/identity/fleet_provisioning/main.cpp, samples/jobs/describe_job_execution/main.cpp, samples/mqtt/basic_pub_sub/main.cpp, samples/mqtt/raw_pub_sub/main.cpp, samples/shadow/shadow_sync/main.cpp
ISSUE:
Currently, the "Getting Started Kit" vended by the IoT console vends a policy that doesn't match the strings used by any V2 SDK samples. So they fail right off the bat 😢
SOLUTION:
Let's get all the V2 SDKs using the same strings, then we can create a policy to fit them all. I'd like to put wildcards in the new policy so users can toy around a little bit, but include the word "test" everywhere so they feel inclined to change it before they ship.
Also, let's get all the samples putting randomness into the client-id, since colliding IDs are a frequent source of confusion.
=> All V2 SDK samples can share policies.

secure_tunneling/CMakeLists.txt, secure_tunneling/include/aws/iotsecuretunneling/SecureTunnel.h, secure_tunneling/source/SecureTunnel.cpp, secure_tunneling/tests/SecureTunnelTest.cpp
For memory that will be passed into the C layer, make a copy and store within the C++ secure tunnel object.
=> Make copy if need to pass address to C layer

secure_tunneling/source/SecureTunnel.cpp
* Not all member variables are initialized/assigned
* Initialize/assign all member variables
=> Assign all member variables in move copy constructor and move assignment operator

secure_tunneling/include/aws/iotsecuretunneling/SecureTunnel.h, secure_tunneling/source/SecureTunnel.cpp, secure_tunneling/tests/SecureTunnelTest.cpp
* Update `aws-c-iot` git submodule to include this [PR](https://github.com/awslabs/aws-c-iot/pull/39)
* Wire `root_ca` to the C layer
=> Wire root_ca to the C layer

samples/mqtt/raw_pub_sub/main.cpp
=> Fixed help

secure_tunneling/include/aws/iotsecuretunneling/SecureTunnel.h, secure_tunneling/source/SecureTunnel.cpp, secure_tunneling/tests/SecureTunnelTest.cpp
The aws-c-iot SDK is updated to notify the client when a websocket is closed. This PR wires the callback in the C++ layer.
This PR depends on a PR in aws-c-iot:
https://github.com/awslabs/aws-c-iot/pull/42
=> Handle shutdown

samples/mqtt/basic_pub_sub/main.cpp, samples/mqtt/raw_pub_sub/main.cpp
* Update crt to 0.13.7 to pull in some bugfixes
* Update mqtt samples to also support direct mqtt connections via an http proxy
=> Update proxy-aware samples with new proxy options

README.md
README incorrectly specifies GCC4.4 as the minimum required version. Full C++11 support requires at least 4.8.
=> Updated GCC minimum in README from 4.4 to 4.8

samples/README.md
Added additional documentation about how the sample must be run from a Greengrass Component with the appropriate policy
=> Update samples/README.md for GG IPC

.gitmodules, devicedefender/include/aws/iotdevicedefender/DeviceDefender.h, devicedefender/source/DeviceDefender.cpp, devicedefender/tests/DeviceDefenderTest.cpp
* These changes are downstream of these changes: https://github.com/awslabs/aws-c-iot/pull/48 and remain in draft until it is pushed and given a pre-release tag
* The interface to start a DeviceDefender task has been updated for better safety and extensibility to include custom metrics. This device SDK needed updates to adhere to the new interface
* No functionality for custom metrics has been added yet
=> Updated DeviceDefender task interface changes

CMakeLists.txt
* Fixes brazil build, includes were not being found
=> Make iot sdk target actually use CRT library target

.github/workflows/ci.yml
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/292
Also, update CI since github docker commands were failing again.
=> Update crt to address mqtt websocket connect crash

.github/workflows/ci.yml
**Issue:**
Some customers are encountering mysterious crashes in some of these functions. Give them the ability to disable them while we attempt to diagnose the issue.
**Description of changes:**
Set `-DUSE_CPU_EXTENSIONS=OFF` to disable CPU-specific functions. This build flag is `ON` by default.
This feature comes by updating submodule aws-crt-cpp: v0.17.0 -> v0.17.1
=> New build flag: USE_CPU_EXTENSIONS

eventstream_rpc/tests/EchoTestRpcModel.cpp, eventstream_rpc/tests/include/awstest/EchoTestRpcClient.h, eventstream_rpc/tests/include/awstest/EchoTestRpcModel.h, format-check.sh, greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcClient.h, greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcModel.h, greengrass_ipc/source/GreengrassCoreIpcModel.cpp
* formatting
* new windowsUser member to RunInfo
=> windowsUser addition to RunInfo

eventstream_rpc/include/aws/eventstreamrpc/EventStreamClient.h, eventstream_rpc/tests/EchoTestRpcClient.cpp, eventstream_rpc/tests/EchoTestRpcModel.cpp, eventstream_rpc/tests/include/awstest/EchoTestRpcClient.h, eventstream_rpc/tests/include/awstest/EchoTestRpcModel.h, greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcClient.h, greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcModel.h, greengrass_ipc/source/GreengrassCoreIpcClient.cpp, greengrass_ipc/source/GreengrassCoreIpcModel.cpp
New approach to GG IPC operation management.
* Make ClientContinuationHandler's destructor virtual so that it can actually be used as a pointed-to value
* ClientOperation uses public inheritance so that we can use the virtual destructor
* Most importantly, a new set of per-operation APIs that return a pointer to the operation, not the operation's value itself
* The new pointer-returning APIs that use a stream handler take the stream handler by shared ptr to guarantee the handler lives sufficiently long 
=> Greengrass IPC API updates

samples/README.md
This PR makes a few minor changes to the README in the `samples` folder. The changes are:
* Removes text mentioning the interactive mode in the pub-sub sample
* Changes `path to root CA` to `path to root CA1` to clarify which CA file is expected in the pub-sub sample
* Adds a section for running the pub-sub example using websockets
* I'm not totally sure if the linked AWS document is the one that should be pointed to - there may be a better file to point to.
* Added a command example to the Raw MQTT Pub-Sub sample. Also added a sentence mentioning the use of `exit` to quit the sample.
* Added a command example to the Shadow sample. Also added a sentence mentioning the use of `quit` to quit the sample.
* Changed the policy for the Jobs sample to the policy found …
=> Minor modifications to the sample README file

samples/shadow/shadow_sync/main.cpp
Modifies the Shadow sample to show how to clear properties, either individually or by clearing the entire state. Now if you enter `null` it will clear the `shadow_property` property in the Shadow document, and if you enter `clear_shadow` it will clear all the fields in `desired` and `reported`.
Also adjusted code for printing the reported shadow updated so it does not get a segmentation fault when `null` is returned.
__________
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*
=> Updated Shadow sample to allow clearing properties by passing null

samples/greengrass/basic_discovery/CMakeLists.txt, samples/greengrass/basic_discovery/main.cpp, samples/greengrass/ipc/CMakeLists.txt, samples/greengrass/ipc/main.cpp, samples/identity/fleet_provisioning/CMakeLists.txt, samples/identity/fleet_provisioning/main.cpp, samples/jobs/describe_job_execution/CMakeLists.txt, samples/jobs/describe_job_execution/main.cpp, samples/mqtt/basic_pub_sub/CMakeLists.txt, samples/mqtt/basic_pub_sub/main.cpp, samples/mqtt/pkcs11_pub_sub/CMakeLists.txt, samples/mqtt/pkcs11_pub_sub/main.cpp, samples/mqtt/raw_pub_sub/CMakeLists.txt, samples/mqtt/raw_pub_sub/main.cpp, samples/secure_tunneling/secure_tunnel/CMakeLists.txt, samples/secure_tunneling/secure_tunnel/main.cpp, samples/secure_tunneling/tunnel_notification/CMakeLists.txt, samples/secure_tunneling/tunnel_notification/main.cpp, samples/shadow/shadow_sync/CMakeLists.txt, samples/shadow/shadow_sync/main.cpp, samples/utils/CommandLineUtils.cpp, samples/utils/CommandLineUtils.h
Refactors command line parsing into a single file shared across all samples. This reduces the duplicate code, makes the samples smaller, and also has the benefit of additions made to the command line parsing file benefiting all samples.
This PR modifies all of the samples to use this shared file, modifies some wording for better consistency across samples, and adjusts the secure_tunnel sample to use the `Aws::String` class instead of `std::string`.
_____________
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*
=> Refactor of command line argument parsing to single file

identity/source/IotIdentityClient.cpp, jobs/source/IotJobsClient.cpp, samples/jobs/describe_job_execution/main.cpp, secure_tunneling/source/IotSecureTunnelingClient.cpp, shadow/source/IotShadowClient.cpp
Fixes issue where a segmentation fault will occur if a uninitialized shared pointer is passed in the constructor of the IoT Client classes (Job, Shadow, Secure Tunnel, etc).
___________
=> Fix segmentation fault in iot client init functions

eventstream_rpc/include/aws/eventstreamrpc/EventStreamClient.h, eventstream_rpc/source/EventStreamClient.cpp
Fixes a memory leak in event stream due to `ContinuationCallbackData` being held by the actual connection and only destroyed on connection shutdown. This means that every single request will cause a leak of ~127 bytes which won't be cleaned until the whole connection dies. This change removes the vector of callback data from the connection and instead stores the continuation callback data with the actual continuation which created it. It is then destroyed in the continuation's destructor.
=> fix(eventstream): move ContinuationCallbackData into ClientContinuation to fix memory leak

eventstream_rpc/source/EventStreamClient.cpp
Previous change #436 introduced a bug on destruction of the ClientContinuationHandler which throws SIGABT on macos due to trying to use a mutex on a freed object. This change fixes that and simplifies the destruction, putting ClientContinuation in charge of it.
=> fix(eventstream): move callback data shutdown into ClientContinuation destructor

samples/README.md
Adds a note to mention the default client ID used for the samples, reducing confusion on what client ID is needed. This is especially helpful if you are transitioning from the V1 SDK and are trying to use a V1 SDK sample policy, as the V1 SDK samples use a different default client ID.
__________
=> Mention the default ClientID in the sample readme

samples/device_defender/basic_report/main.cpp, samples/greengrass/basic_discovery/main.cpp, samples/greengrass/ipc/main.cpp, samples/identity/fleet_provisioning/main.cpp, samples/jobs/describe_job_execution/main.cpp, samples/mqtt/basic_connect/main.cpp, samples/mqtt/custom_authorizer_connect/main.cpp, samples/mqtt/pkcs11_connect/main.cpp, samples/mqtt/raw_connect/main.cpp, samples/mqtt/websocket_connect/main.cpp, samples/mqtt/windows_cert_connect/main.cpp, samples/mqtt/x509_credentials_provider_connect/main.cpp, samples/pub_sub/basic_pub_sub/main.cpp, samples/secure_tunneling/secure_tunnel/main.cpp, samples/secure_tunneling/tunnel_notification/main.cpp, samples/shadow/shadow_sync/main.cpp, samples/utils/CommandLineUtils.cpp, samples/utils/CommandLineUtils.h
Adds the `verbosity` command to all of the samples, making it easier to debug without needing to recompile when you want to change logging verbosity. Also increases consistency with the other SDKs.
(*Also removed `ca_file` from the custom authorizer sample as it is not used in the sample.*)
__________
=> Add verbosity command to samples

.github/workflows/ci.yml
Set github.head_ref as env in CI
=> Set github.head_ref as env in CI

README.md
**Issue:**
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/499
User encountering crashes when they build an application that used the IoT SDK and libcurl, which created a dependency on two different versions of libcrypto.
**Description of Changes:**
Explain the `-DUSE_OPENSSL=ON` build option, and when you'd want to use it.
=> document using system installation of libcrypto

.github/workflows/release.yml
Fixes a super minor mistake in the release YAML. In my testing repository I had the environment variable as `GH_TOKEN` but in this repository (and the others) I renamed it to `GITHUB_TOKEN` but forgot to change it in the YAML 🤦 
____________
=> Fix minor mistake in release YAML

utils/publish-release.sh
Our CD currently makes annotated tags due to passing a tag title when we make the tag in CD. This has the unfortunate side effect of making TWO tags each time we make a release because of how the annotated tag system works: One that is a lightweight tag that just points to the commit, and then another tag that points to both the lightweight tag AND the commit. This leads to having tags with `<tag>^{}` in it. Tested and removing passing a message makes the CD pipeline only send a lightweight tag, fixing the issue.
Will fix #519 for **future** CD releases.
____________
=> Only make lightweight tags in CD

utils/update_semantic_version.py
The script had a silly error where it would prevent releases if the tag had `0` at ANY point rather than preventing releases if the tag is ONLY `0.0.0`.
This PR fixes that issue.
________
=> Fix release script failing on releases with zero

samples/mqtt5/mqtt5_shared_subscription/README.md, samples/mqtt5/mqtt5_shared_subscription/main.cpp
Makes a quick adjustment to the README of the shared subscription sample to adjust its wording. Also removes the note about MQTT5 being in developer preview from the sample source directly.
________
=> Shared Subscription sample readme adjustment

documents/Secure_Tunnel_Userguide.md, secure_tunneling/include/aws/iotsecuretunneling/SecureTunnel.h, secure_tunneling/source/SecureTunnel.cpp
* Add option to provide tls options when building a new secure tunnel
=> optional tls settings on secure tunnel creation

samples/mqtt5/mqtt5_shared_subscription/README.md, samples/mqtt5/mqtt5_shared_subscription/main.cpp
Makes a few minor changes to better fit the AWS docs for shared subscriptions. Also adds more logging and removes some temporary code added for compatibility prior to shared subscription support public release.
________
=> Adjust shared subscription sample to better fit docs

samples/utils/CommandLineUtils.cpp
Adjusts the Greengrass basic discovery sample to take `--region` instead of `--signing_region` for backwards compatibility with the Greengrass documentation.
________
=> Adjust command input for backwards compatibility

devicedefender/CMakeLists.txt, discovery/CMakeLists.txt, eventstream_rpc/CMakeLists.txt, greengrass_ipc/CMakeLists.txt, identity/CMakeLists.txt, iotdevicecommon/CMakeLists.txt, secure_tunneling/CMakeLists.txt, shadow/CMakeLists.txt
**Issue:**
If a windows user does:
```
cmake -B build -S .
cmake --build build --config Release
```
Their Release code will compile with `-DDEBUG_BUILD` defined.
**Description of Changes:**
CMake scripts should use `$<CONFIG>` generator expressions, instead of checking `${CMAKE_BUILD_TYPE}`. Multi-config generators like Visual Studio ignore `CMAKE_BUILD_TYPE`, so many users (and IDEs like VSCode with the CMake Tools plugin) don't bother setting `CMAKE_BUILD_TYPE`. See: https://cmake.org/cmake/help/v3.22/manual/cmake-buildsystem.7.html#build-configurations
=> Stop checking CMAKE_BUILD_TYPE in CMake scripts

eventstream_rpc/source/EventStreamClient.cpp
Failed Connect() was not setting client state to DISCONNECTED from CONNECTING_SOCKET which caused a deadlock in destructor for EventStreamClient. Pulling in changes from this PR: https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/631 
=> Fix deadlock in destruction of Eventstream Client

discovery/include/aws/discovery/ConnectivityInfo.h, discovery/source/ConnectivityInfo.cpp, discovery/source/DiscoveryClient.cpp, eventstream_rpc/include/aws/eventstreamrpc/EventStreamClient.h, samples/device_defender/basic_report/main.cpp, samples/device_defender/mqtt5_basic_report/main.cpp, samples/fleet_provisioning/mqtt5_fleet_provisioning/main.cpp, samples/greengrass/basic_discovery/main.cpp, samples/jobs/mqtt5_job_execution/main.cpp, samples/mqtt/basic_connect/main.cpp, samples/mqtt/cognito_connect/main.cpp, samples/mqtt/websocket_connect/main.cpp, samples/mqtt5/mqtt5_pubsub/main.cpp, samples/pub_sub/basic_pub_sub/main.cpp, samples/secure_tunneling/secure_tunnel/main.cpp, samples/shadow/mqtt5_shadow_sync/main.cpp, samples/shadow/shadow_sync/main.cpp, servicetests/tests/FleetProvisioning/main.cpp, servicetests/tests/JobsExecution/main.cpp, servicetests/tests/ShadowUpdate/main.cpp
Issue: https://github.com/awslabs/aws-c-io/issues/576
=> Change `port` from uint16_t to uint32_t, to support VSOCK

.builder/actions/build_samples.py, .github/workflows/ci.yml, utils/run_sample_ci.py
=> Fix and Enable Windows Cert Store Test

README.md, documents/MIGRATION_GUIDE.md
Migration guide to help customer move from the V1 sdk to the V2 sdk
=> Migrate from V1 to V2  Guide

make-docs.py
Add a special file disabling nojekyll on gh-pages.
I verified this fix in a fork, disabling jekyll **does not** change how the pages look.
Main repo returns 404: https://aws.github.io/aws-iot-device-sdk-cpp-v2/_greengrass_core_ipc_model_8h_source.html
Fork repo works: https://sfod.github.io/aws-iot-device-sdk-cpp-v2/_greengrass_core_ipc_model_8h_source.html
=> Disable nojekyll on gh-pages

.github/workflows/ci.yml, samples/secure_tunneling/secure_tunnel/main.cpp, samples/secure_tunneling/tunnel_notification/main.cpp
=> Fix compiler matrix versions

.github/workflows/ci.yml
- Add macos-13 image to OSX job.
- Use Python virtual env to install packages. 
=> Fix macos CI job

greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcModel.h, greengrass_ipc/source/GreengrassCoreIpcModel.cpp
=> Update Greengrass IPC

samples/device_defender/mqtt5_basic_report/main.cpp, samples/fleet_provisioning/fleet_provisioning/main.cpp, samples/fleet_provisioning/mqtt5_fleet_provisioning/main.cpp, samples/jobs/mqtt5_job_execution/main.cpp, samples/mqtt5/mqtt5_pubsub/main.cpp, samples/mqtt5/mqtt5_shared_subscription/main.cpp, samples/secure_tunneling/secure_tunnel/main.cpp, samples/shadow/mqtt5_shadow_sync/main.cpp, servicetests/tests/FleetProvisioning/main.cpp
There are race conditions in Fleet provisioning service tests and Secure tunnel sample (caught by this PR https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/703).
- I recently fixed a race condition in Fleet provisioning **sample**, so I reused that code in Fleet provisioning service tests.
- Secure tunnel sample used `sleep` to sync two threads, I added a promise.
- Additional change: use std::unique_ptr instead of raw pointers in samples.
=> Fix race conditions in samples and service tests

samples/mqtt5/mqtt5_pubsub/main.cpp, samples/mqtt5/mqtt5_shared_subscription/main.cpp
In MQTT5 protocol, if subscription fail, SubAck packet not necessarily contains a reason string. In MQTT5 samples, we try to print a SubAck reason string unconditionally, which sometimes crashes samples.
The same applies to publish operations.
Add check for a reason string value before using it.
=> Check reason string in MQTT5 samples

samples/shadow/mqtt5_shadow_sync/main.cpp, samples/shadow/shadow_sync/main.cpp
When multiple instances of shadow samples are running in CI, they use the same thing and interfere with each other causing crashes:
```
Received shadow document.
Shadow contains "color". Updating local value to "Shadow_Value_0"...
stderr:
terminate called after throwing an instance of 'std::future_error'
what():  std::future_error: Promise already satisfied
```
Handle multiple incoming shadow messages.
=> Fix shadow samples in CI

.github/workflows/ci.yml, .github/workflows/release.yml
We rely on qemu to test aarch64 on x86-64 github runners.
Qemu had a bug where they had a bug with incorrectly mapping address space. That mostly worked fine until kernel patch that increased entropy in their address randomization. TLDR; qemu likes to segfault a lot against new kernels on our aarch64 test. Solution is to switch to a different github qemu user static image that forces a latest version of qemu, that has the bug fixed.
if you want to read more - https://github.com/tonistiigi/binfmt/issues/240
=> Fix arm based ci

eventstream_rpc/include/aws/eventstreamrpc/EventStreamClient.h, eventstream_rpc/source/EventStreamClient.cpp
Currently, headers from MessageAmendment are not added to header list that will be sent to a server.
Add headers from MessageAmendment object.
Fix move semantics related to MessageAmendment.
=> Fix setting headers in eventstream-rpc

samples/greengrass/basic_discovery/main.cpp
The Greengrass basic discovery sample sometimes deadlock on attempting to establish an MQTT connection.
Remove waiting on a promise from a callback executed by the event loop.
=> Fix deadlock in discovery sample

documents/MIGRATION_GUIDE.md
The rendering of the connection types table in the migration guide is [broken](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/v1.36.0/documents/MIGRATION_GUIDE.md#connection-types-and-features).
Properly specify UTF-8 symbol.
=> Fix migration guide rendering

.github/workflows/ci.yml, README.md
Remove clang-3 from CI
CI uses aws-crt-builder, which when instructed to use clang-3, has failed to find it and has been falling back on GNU 7.5 for the past year+. This means while clang-3 is listed in our CI as having been tested, it isn't. Fixing aws-crt-builder to use clang-3 has revealed a large number of build failures across aws-c-* libraries. Lack of issues related to this implies that clang-3 is not in use and can be removed from CI.
=> Remove clang-3 from CI

documents/MIGRATION_GUIDE.md, documents/MQTT5_Userguide.md, samples/commands/commands-sandbox/main.cpp, samples/deprecated/fleet_provisioning/mqtt5_fleet_provisioning/main.cpp, samples/deprecated/jobs/mqtt5_job_execution/main.cpp, samples/deprecated/shadow/mqtt5_shadow_sync/main.cpp, samples/device_defender/mqtt5_basic_report/main.cpp, samples/mqtt5/mqtt5_pubsub/main.cpp, samples/mqtt5/mqtt5_shared_subscription/main.cpp, samples/secure_tunneling/secure_tunnel/main.cpp, secure_tunneling/source/SecureTunnel.cpp, secure_tunneling/tests/main.cpp, servicetests/tests/FleetProvisioning/main.cpp, servicetests/tests/JobsExecution/main.cpp, servicetests/tests/ShadowUpdate/main.cpp
Related to https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/809 (but doesn't resolve it).
IoT SDK v2 should use CRT internal allocator whenever possible.
Replace `std::make_shared` with `Aws::Crt::MakeShared`.
=> Replace std::make_shared with Crt::MakeShared

.github/workflows/ci.yml, eventstream_rpc/source/EventStreamClient.cpp
- Windows 2019 will be fully unsupported by 2025-06-30, https://github.com/actions/runner-images/issues/12045. Remove it with msvc-15 and below.
- Use latest windows-2025 and msvc-17
=> Use windows-2025 image in CI

samples/service_clients/fleet_provisioning/provision-basic/main.cpp, samples/service_clients/fleet_provisioning/provision-csr/main.cpp
Const ref doesn't always prolong the lifetime of a variable.
It's possible to still use const ref by splitting getting the future value into multiple statements. But using value semantics is also fine as move semantics will be used.
=> Fix fleet provisioning samples
