aws/aws-iot-device-sdk-cpp-v2

README.md, samples/jobs/describe_job_execution/main.cpp, samples/shadow/shadow_sync/main.cpp
Latest version of all dependencies.
Removes Mqtt::ConnectionState enum
=> Update to aws-crt-cpp v0.4.0

README.md
=> Incremented version number for crt dependency.

README.md, codebuild/common-posix.sh, codebuild/common-windows.bat
=> Updated version number for crt to v0.4.4

README.md
*Issue #, if available:* https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/issues/57
=> Updated version of aws-crt-cpp required to build

aws-common-runtime/CMakeLists.txt, codebuild/common-posix.sh, codebuild/common-windows.bat, discovery/source/DiscoveryClient.cpp
=> Http API change + update to CRT v0.5.4

README.md, aws-common-runtime/CMakeLists.txt
=> Updated dependency versions.

aws-common-runtime/CMakeLists.txt
=> Update crt dependency to 0.6.3

aws-common-runtime/CMakeLists.txt
=> Updates for crt to pick up windows security fixes.

aws-common-runtime/CMakeLists.txt
=> Update to v0.6.7 of crt.

aws-common-runtime/CMakeLists.txt
=> Fix leak in websockets.

aws-common-runtime/CMakeLists.txt
=> Fix stream leak in sts provider

README.md
=> docs: fix path to repo

jobs/source/JobExecutionData.cpp, jobs/source/JobExecutionState.cpp, jobs/source/RejectedError.cpp, jobs/source/UpdateJobExecutionRequest.cpp
*Issue #, if available:* https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/95
*Description of changes:* Fixing serialization bug with enumerations so that they are added to the JSON output of each respective SerializeToObject method.
=> Fixing serialization bug with enumerations

samples/mqtt/basic_pub_sub/main.cpp
* adds x509 command line options to the basic pub sub example
=> Add x509 support to basic pub sub

samples/mqtt/basic_pub_sub/main.cpp
* Rework websocket config to always create a credentials provider manually
=> Fix x509 sample not actually using the x509 provider in lieu of default provider

README.md
=> README warns about Windows path lengths

secure_tunneling/CMakeLists.txt, secure_tunneling/tests/CMakeLists.txt, secure_tunneling/tests/SecureTunnelTest.cpp
=> Add secure tunneling unit tests

CMakeLists.txt, secure_tunneling/CMakeLists.txt, secure_tunneling/cmake/IotSecureTunneling-cpp-config.cmake, secure_tunneling/include/aws/iotsecuretunneling/Exports.h, secure_tunneling/include/aws/iotsecuretunneling/SecureTunnel.h, secure_tunneling/source/SecureTunnel.cpp, secure_tunneling/tests/CMakeLists.txt, secure_tunneling/tests/SecureTunnelTest.cpp
* Add secure tunneling as top level feature
=> Add Secure Tunneling

secure_tunneling/CMakeLists.txt, secure_tunneling/include/aws/iotsecuretunneling/Exports.h, secure_tunneling/include/aws/iotsecuretunneling/IotSecureTunnelingClient.h, secure_tunneling/include/aws/iotsecuretunneling/SecureTunnelingNotifyResponse.h, secure_tunneling/include/aws/iotsecuretunneling/SubscribeToTunnelsNotifyRequest.h, secure_tunneling/source/IotSecureTunnelingClient.cpp, secure_tunneling/source/SecureTunnelingNotifyResponse.cpp, secure_tunneling/source/SubscribeToTunnelsNotifyRequest.cpp
Add for subscribing to thing notify
=> Add Secure Tunneling Notify

README.md
added windows specific build guide
=> Windows build guide

FAQ.md, README.md
Add FAQ for c++ and clean up readme
=> IoT c++ FAQ

samples/greengrass/basic_discovery/main.cpp, samples/mqtt/basic_pub_sub/main.cpp, samples/mqtt/raw_pub_sub/main.cpp
Use new callback type that has more data in it.
=> Use newer MQTT on-message callback in samples

secure_tunneling/tests/SecureTunnelTest.cpp
* Update to new managed thread join system. Addresses https://github.com/awslabs/aws-crt-cpp/issues/190
=> Update submodule and test to new thread join API

samples/mqtt/basic_pub_sub/main.cpp, samples/mqtt/raw_pub_sub/main.cpp
=> cutomer do not need to hold the payload until publish complete

.gitmodules
=> shorten path

codebuild/samples/linux-smoke-tests.yml, codebuild/samples/pubsub-linux.sh, codebuild/samples/setup-linux.sh, samples/mqtt/basic_pub_sub/main.cpp
* Add direct mqtt and websocket runs of basic_pub_sub to CI
=> Pubsub in ci

PREREQUISITES.md, README.md
Improved README. Added instructions for pre-requisites (PREREQUISITES.md) of building the SDK for Windows. 
=> Improve Installation Instructions for Windows

discovery/include/aws/discovery/DiscoveryClient.h, discovery/source/DiscoveryClient.cpp, samples/greengrass/basic_discovery/main.cpp, samples/greengrass/ipc/main.cpp, samples/identity/fleet_provisioning/main.cpp, samples/jobs/describe_job_execution/main.cpp, samples/mqtt/basic_pub_sub/main.cpp, samples/mqtt/pkcs11_pub_sub/main.cpp, samples/mqtt/raw_pub_sub/main.cpp, samples/secure_tunneling/secure_tunnel/main.cpp, samples/secure_tunneling/tunnel_notification/main.cpp, samples/shadow/shadow_sync/main.cpp, secure_tunneling/include/aws/iotsecuretunneling/SecureTunnel.h, secure_tunneling/source/SecureTunnel.cpp
Simplifies the samples using the builder simplification changes made in [this PR](https://github.com/awslabs/aws-crt-cpp/pull/333). This reduces the code needed for starting an MQTT connection by using default static singletons.
Requires the following PR on the crt-cpp repository to function correctly: [PR 333](https://github.com/awslabs/aws-crt-cpp/pull/333).
(*Note - without the changes in the linked PR the builds will fail*)
________
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*
=> Connection builder simplification

PREREQUISITES.md
Added MacOS and Linux install instructions for installing Clang, GCC, and CMake.
____________
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*
=> Add MacOS and Linux install instructions to PREREQUISITES.md

samples/shadow/shadow_sync/main.cpp, shadow/include/aws/iotshadow/ShadowDeltaUpdatedEvent.h, shadow/source/ShadowDeltaUpdatedEvent.cpp
Adds ClientToken to the ShadowDeltaUpdated state to better follow the documentation. 👍
___________
=> Added ClientToken to ShadowDeltaUpdated

PREREQUISITES.md
Updates the prerequisites file structure a bit for better flow. Also added additional information and instructions.
_________
=> Updated PreRequisites file

README.md
Updates the README install instructions so they are easier to follow and includes running a git submodule update command, as it's an easy check to make sure all the submodules are updated and doesn't cause any harm if all the submodules are already update to date.
_______
=> Readme Install Instructions Update

samples/README.md
Adds a note on the supported data formats and types for Device Defender.
______
=> Added note on supported data requirements for Device Defender

.github/workflows/closed-issue-message.yml, .github/workflows/docs.yml, .github/workflows/stale_issue.yml
because actions in this repo no longer have write permission by default.
=> Give explicit permissions to Github actions

.github/workflows/license-check.yml
Issue #, if available:
NA
Description of changes:
This action checks for the files modified by a PR and scans them for Licenses, failing if it finds a new license added, removed or modified.
For this check failure doesn't mean "don't merge" but "make sure it's safe".
There will be false positives on the license detection, but there should be no false negatives.
[KaibaLopez](https://github.com/KaibaLopez) commented [on Oct 14, 2021](https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/336#issue-1026722765)
=> add license checker

greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcClient.h, greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcModel.h, greengrass_ipc/source/GreengrassCoreIpcClient.cpp, greengrass_ipc/source/GreengrassCoreIpcModel.cpp
=> Put component metric

samples/greengrass/ipc/main.cpp
Part of https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/465
=> Fix GG IPC sample for earlier breaking API change

.builder/actions/build_samples.py
=> added greengrass/ipc sample to build in ci

samples/README.md, samples/secure_tunneling/secure_tunnel/main.cpp
Improved sample readme for Secure Tunnel sample.
Fixed bug related to local_proxy_mode_source command line flag bug
=> Secure Tunnel README and bug fix

greengrass_ipc/source/GreengrassCoreIpcClient.cpp, greengrass_ipc/source/GreengrassCoreIpcModel.cpp
Adds headers to all generated Greengrass code so it is easier to know what is generated from a model, and what is not. Also adds the copyright.
________
=> Add generated headers to Greengrass generated code

.github/workflows/ci.yml, samples/device_defender/basic_report/main.cpp, samples/jobs/describe_job_execution/main.cpp, samples/pub_sub/cycle_pub_sub/main.cpp, samples/secure_tunneling/secure_tunnel/main.cpp, samples/shadow/shadow_sync/main.cpp
=> Initial Alpine CI

samples/utils/CommandLineUtils.cpp, samples/utils/CommandLineUtils.h
Add option in samples to save logs to a file.
=> Add option to save logs to file

README.md, documents/FAQ.md, documents/MQTT5_Userguide.md, samples/README.md
=> Update Mqtt5 Docs

.github/workflows/release.yml
Adjusts the release token to one in secrets
__________
=> Use the right token in the release script

docsrc/doxygen.config
Fix the main page not being included in the documentation.
________
=> Add the main page to the documentation

documents/Secure_Tunnel_Userguide.md
Add Multiplexing Information to Secure Tunnel Guide
=> add multiplexing information to guide

docsrc/mainpage.md
Just adds a trivial change to retrigger documentation deployment.
_________
=> Trivial documentation change

samples/mqtt5/mqtt5_pubsub/main.cpp, samples/mqtt5/mqtt5_shared_subscription/main.cpp, samples/pub_sub/basic_pub_sub/main.cpp
Fixes a display issue when viewed via the MQTT client on AWS.
___________
=> Adjust MQTT5 and MQTT PubSub samples to output JSON

samples/utils/CommandLineUtils.cpp, samples/utils/CommandLineUtils.h
* Accept both "region" or "signing_region" arguments
=> Sample region argument

secure_tunneling/source/SecureTunnel.cpp
- Bring in the changes from https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/594
- Update byte buffer allocation
=> Fix Secure Tuneling Exceptions

greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcClient.h, greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcModel.h, greengrass_ipc/source/GreengrassCoreIpcClient.cpp, greengrass_ipc/source/GreengrassCoreIpcModel.cpp
=> Update model and client for GG 2.11

documents/FAQ.md
Add note to FAQ about blocking in callbacks
=> Add note to FAQ about blocking in callbacks

documents/Secure_Tunnel_Userguide.md
Update the Secure Tunnel User Guide
=> update the secure tunnel user guide

samples/mqtt/cognito_connect/README.md
Doc: Add new permission policy to the Cognito Readme
=>  Doc: Update Cognito sample Readme to add permissions

documents/Secure_Tunnel_Userguide.md, samples/secure_tunneling/secure_tunnel/README.md
* Update aws-c-iot to provide additional checks for and to fix minor issues in secure tunnel
* Fix parameter name in secure tunnel readme
=> Bump aws-c-iot version

.github/workflows/ci.yml, eventstream_rpc/include/aws/eventstreamrpc/EventStreamClient.h, eventstream_rpc/tests/include/awstest/EchoTestRpcClient.h, eventstream_rpc/tests/include/awstest/EchoTestRpcModel.h, greengrass_ipc/CMakeLists.txt, greengrass_ipc/include/aws/greengrass/Exports.h, greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcClient.h, greengrass_ipc/include/aws/greengrass/GreengrassCoreIpcModel.h
=> Codegen shared libs export

.github/workflows/ci.yml
signing cert is expired and we shouldn't be doing it this way anyways
=> Disable the Pkcs12 test

documents/MQTT5_Userguide.md, samples/mqtt5/mqtt5_pubsub/README.md, samples/mqtt5/mqtt5_shared_subscription/README.md
=> Mqtt5 General Avalibility

.github/workflows/ci.yml
=> Use aws-actions/configure-aws-credentials@v2

documents/MIGRATION_GUIDE.md
=> Fix timeout in v1

tests/greengrass/basic_discovery/hello_world_subscriber.py
=> Add copyright header

samples/utils/CommandLineUtils.h
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/725
remove unused private variable from samples
=> remove m_internal_client

samples/fleet_provisioning/fleet_provisioning/main.cpp, samples/fleet_provisioning/mqtt5_fleet_provisioning/main.cpp
=> Fix race conditions in fleet provisioning samples

secure_tunneling/source/SecureTunnel.cpp
Fixes unused parameter in SecureTunnel.c as brought to attention here: https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/773
=> Fix unused parameter in SecureTunnel
